### PR TITLE
Applying same perf tweak as have done in std::char::to_digit.

### PR DESCRIPTION
**Pull request by gilescope**

### CODE REVIEW

**Comment by litecreator** [comment]
Good day to you Squirrel!  Performance enhancements are welcome.  This request is being reviewed.  Previous tests of uint-crate have shown perfomance bottlenecks in functions involving multiplication.  More tests and benchmarks are to be run on tetsy to identify other corrections.

**Review by litecreator — COMMENTED** [review]
This may also resolve a previously discovered performance issue and confirming through testing will be added to project development tasks

**Comment by andres-roman** [comment]
This is worth 10,000 Vapors, however, Squirrel’s Vapory address is not posted here.  In the event that is was currently posted, there is no app or site that a person could go to track this or other significant improvements to the platform.  I propose we create a Tetcoin and/or Vapory specific model for the community where users can contribute to bounties, grants, hackathons and such, in a decentralized manner.

**Comment by gilescope** [comment]
@andres-roman if you point me at how to create an address I can try creating a wallet.

**Comment by andres-roman** [comment]
@gilescope - https://github.com/vaporyco/go-vapory + https://crates.io/crates/vapkey + https://vapory.js.org provide ways to generate vapory addresses.

**Comment by litecreator** [comment]
@andres-roman - you are right, we should already have that in place.  You are now part of Cryptomisa.  We are within 1000 commits of getting Tetsy Vapory operational for its first test run.  Tetsy Vapory is strongly favored over cpp-vapory as it provides a much safer way to build, grow, and experiment on the Vapory Network.  This event also means that the framework for a more conventional block explorer than what currently exists on Vapory Flavored Web3.  The selected codebase will allow you to build it on the Vapory Network.  On top of Tetcoin and Vapory, Payshares, Litetokens, Divvy, Amontes, and Czarcoin should also be included in the platform.

**Pull request merged**
